### ISSUE TITLE
Dtype of variables

### ISSUE THREAD

**Issue by Bihaqo** [Bihaqo/t3f#182]
Variables dtype is float32_ref which is sometimes problematic (e.g. project_sum(?, variable, weights) will convert weights to tensor with dtype=float_ref

Use .base_dtype

**Comment by SunYanCN** [comment]
I meet this problem, how I can fix it?

**Comment by Bihaqo** [comment]
I'll fix it in a few days

**Comment by Bihaqo** [comment]
Turns out you just need to do `tf.enable_resource_variables()` at the beginning of your program.
