### ISSUE TITLE
Adding support of Eager and newer versions of Tensorflow

### ISSUE THREAD

**Issue by aiboyko** [Bihaqo/t3f#184]
1) The code crashes if one uses tensorflow above 1.11
2) The eager mode is not supported.

To summarize, one needs to learn old arcane syntax to somehow embed t3f into modern DL software stack. In order to use it one needs to do some homunculus code that runs  (tf 1.11 + t3f) + (modern tensorflow or pytorch) on the same GPU.

@Bihaqo Could you please add TF 2.0 compatibility and Eager mode when you have time.

**Comment by oseledets** [comment]
You probably need a simple example to reproduce. I think, eager is partially supported.
Also, there is an "upgrade script" that you can try running and help the community.

**Comment by Bihaqo** [comment]
Thanks for creating the issue!

As discussed offline, the eager mode works fine on the example you have in mind.
As for the later versions of tf, that's a good point, I'll add tests for that.

**Comment by Bihaqo** [comment]
#185

**Comment by Bihaqo** [comment]
It seems that tf 1.13.2 and tf 1.14 are fine even without any fixes.
https://travis-ci.org/Bihaqo/t3f/builds/588457426?utm_source=github_status&utm_medium=notification

**Comment by Bihaqo** [comment]
#185 is merged now and t3f should work with latest tf.
