### ISSUE TITLE
version 1.0.0 here and on PyPI are different versions 

### ISSUE THREAD

**Issue by aiboyko** [Bihaqo/t3f#187]
The version that comes from pip install crashes with a tensorflow==1.14, but the version that is stored on github does not. So they are different versions, but by looking just at the number it is impossible to figure out.

I would like to suggest
1) updating the number of this (github) version) to smth like 1.0.1
2) updating the code available from pip install.

**Comment by Bihaqo** [comment]
https://pypi.org/project/t3f/1.1.0/

enjoy
