### ISSUE TITLE
.value leads to errors

### ISSUE THREAD

**Issue by faysou** [Bihaqo/t3f#194]
When using tensorflow 2 and  tensorflow.compat.v1 some functions in "tensor_train_batch.py" and "decompositions.py" have ` .value` after some numbers used for ranks, it leads to the code bugging.
When removing these ` .value` the code works again.

For example in tensor_train_batch.py

    self._batch_size = tt_cores[0].get_shape()[0].value (line 58)

**Comment by Bihaqo** [comment]
TF 2 is not fully supported, you have to use 
```
tf.disable_v2_behavior()
tf.enable_eager_execution()
```
to disable some of v2 features (like in [the tutorial](https://colab.research.google.com/github/Bihaqo/t3f/blob/develop/docs/quick_start.ipynb)).

**Comment by faysou** [comment]
Ok thank you.
