### ISSUE TITLE
TF 2.2 support: tt_rank as float (matrix/tensor_ones/zeros)

### ISSUE THREAD

**Issue by towadroid** [Bihaqo/t3f#211]
Using TF 2.2.0 the functions `matrix_ones` and `matrix_zeros` (edit: same for `tensor_ones` and `tensor_zeros` ) fail because the tt_ranks (l.185 and l.227) are floats and TF does not accept floats anymore. An easy fix is to add `dtype=int`  to the respective statements.

However more parts of the code may be affected. This may also be related to #205 as the functions mentioned above still work fine with TF 2.0.0.

**Comment by Bihaqo** [comment]
Thank you, I'll take a look

**Comment by Bihaqo** [comment]
Sorry it took me so insanely long. Looking into it right now though.

Your fix seems to work (#214): it passes tests locally (but fails on travis with a weird C level error). I jumped immediately to TF 2.4. because apparently everything older than that has security vulnerabilities.
