### ISSUE TITLE
riemannian projection of two tensor train objects fails

### ISSUE THREAD

**Issue by KhrulkovV** [Bihaqo/t3f#80]
The following code 
`projected_grad = t3f.riemannian.project(grad_tt, weight_tt)`
where `grad_tt` and `weight_tt` are TensorTrain objects gives the following error
`ValueError: batch size is not available for a TensorTrain object.`

However, the same piece of code with `t3f.riemannian.project_sum(grad_tt, weight_tt)` instead works

**Comment by Bihaqo** [comment]
Works in the latest version (develop branch)
